[package]
name = "double-ratchets"
version = "0.0.1"
edition = "2024"

[dependencies]
x25519-dalek = { version="2.0.1", features=["static_secrets"] }
chacha20poly1305 = "0.10.1"
blake2 = "0.10.6"
rand_core = "0.6.4"
rand = "0.8.5"
